# Generated by Django 6.0.7 on 2026-08-02 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('period', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='prix (FCFA)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='durée en jours')),
                ('description', models.TextField(blank=True)),
                ('gives_full_catalog_access', models.BooleanField(default=True, help_text="Donne accès à tout le catalogue plutôt qu'à un cours précis")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "formule d'abonnement",
                'verbose_name_plural': "formules d'abonnement",
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='InstructorPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='montant brut (FCFA)')),
                ('platform_commission_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='montant net (FCFA)')),
                ('provider', models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('coris_money', 'Coris Money')], max_length=20)),
                ('payout_phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('paid', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reversement formateur',
                'verbose_name_plural': 'reversements formateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé'), ('pending', 'En attente de paiement')], default='pending', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.subscriptionplan')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='référence interne')),
                ('purpose', models.CharField(choices=[('course_purchase', 'Achat de cours'), ('subscription', 'Abonnement')], max_length=20)),
                ('provider', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('coris_money', 'Coris Money')], max_length=20, verbose_name='opérateur')),
                ('payer_phone_number', models.CharField(max_length=20, verbose_name='numéro payeur')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='montant (FCFA)')),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=128, verbose_name='ID transaction opérateur')),
                ('provider_response_payload', models.JSONField(blank=True, default=dict, verbose_name="réponse brute de l'opérateur")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.subscription')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['status', 'provider'], name='payments_pa_status_eb2eec_idx'), models.Index(fields=['student'], name='payments_pa_student_2c03b7_idx')],
            },
        ),
    ]
