# Generated by Django 6.0.7 on 2026-08-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, help_text='Page PayDunya vers laquelle rediriger le client pour payer.', verbose_name='URL de paiement hébergée'),
        ),
        migrations.AlterField(
            model_name='instructorpayout',
            name='provider',
            field=models.CharField(blank=True, choices=[('paydunya', 'PayDunya (Orange Money / Moov Money / Wave)'), ('orange_money', 'Orange Money (direct)'), ('moov_money', 'Moov Money (direct)'), ('wave', 'Wave (direct)'), ('coris_money', 'Coris Money (direct)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='numéro payeur'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('paydunya', 'PayDunya (Orange Money / Moov Money / Wave)'), ('orange_money', 'Orange Money (direct)'), ('moov_money', 'Moov Money (direct)'), ('wave', 'Wave (direct)'), ('coris_money', 'Coris Money (direct)')], max_length=20, verbose_name='opérateur'),
        ),
    ]
