# Generated by Django 6.0.7 on 2026-08-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_checkout_url_alter_instructorpayout_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorpayout',
            name='provider',
            field=models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('coris_money', 'Coris Money'), ('paydunya', 'PayDunya (agrégateur, en secours)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('coris_money', 'Coris Money'), ('paydunya', 'PayDunya (agrégateur, en secours)')], max_length=20, verbose_name='opérateur'),
        ),
    ]
