# Generated by Django 6.0.7 on 2026-08-02 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_conversions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='courses.course')),
            ],
            options={
                'verbose_name': "lien d'affiliation",
                'verbose_name_plural': "liens d'affiliation",
            },
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='affiliates.affiliatelink')),
            ],
            options={
                'verbose_name': "clic d'affiliation",
                'verbose_name_plural': "clics d'affiliation",
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='taux de commission (%)')),
                ('total_earned', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil affilié',
                'verbose_name_plural': 'profils affiliés',
            },
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='affiliates.affiliateprofile'),
        ),
        migrations.CreateModel(
            name='AffiliateCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='montant de la commission (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('paid', 'Payée'), ('cancelled', 'Annulée (remboursement)')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commission', to='payments.payment')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliates.affiliatelink')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliates.affiliateprofile')),
            ],
            options={
                'verbose_name': "commission d'affiliation",
                'verbose_name_plural': "commissions d'affiliation",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='affiliatelink',
            unique_together={('affiliate', 'course')},
        ),
    ]
