# Generated by Django 6.0.7 on 2026-08-02 00:45

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nom')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='numéro de téléphone')),
                ('role', models.CharField(choices=[('student', 'Étudiant'), ('instructor', 'Formateur'), ('admin', 'Administrateur')], default='student', max_length=20, verbose_name='rôle')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='avatar')),
                ('bio', models.TextField(blank=True, verbose_name='biographie')),
                ('country', models.CharField(blank=True, default='Burkina Faso', max_length=100, verbose_name='pays')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('headline', models.CharField(blank=True, max_length=255, verbose_name='titre professionnel')),
                ('is_verified_instructor', models.BooleanField(default=False, verbose_name='formateur vérifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès admin Django')),
                ('email_verified', models.BooleanField(default=False, verbose_name='e-mail vérifié')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'jeton de vérification e-mail',
                'verbose_name_plural': 'jetons de vérification e-mail',
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_courses', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('payout_provider', models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('coris_money', 'Coris Money'), ('bank', 'Compte bancaire')], max_length=20)),
                ('payout_phone_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil formateur',
                'verbose_name_plural': 'profils formateurs',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'jeton de réinitialisation',
                'verbose_name_plural': 'jetons de réinitialisation',
            },
        ),
    ]
