# Generated by Django 6.0.7 on 2026-08-02 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône (ex: calculator, flask)", max_length=50, verbose_name='icône')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.category', verbose_name='catégorie parente')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='sous-titre')),
                ('description', models.TextField(verbose_name='description')),
                ('what_you_will_learn', models.JSONField(blank=True, default=list, verbose_name='objectifs pédagogiques')),
                ('requirements', models.JSONField(blank=True, default=list, verbose_name='prérequis')),
                ('target_audience', models.JSONField(blank=True, default=list, verbose_name='public visé')),
                ('language', models.CharField(default='Français', max_length=50, verbose_name='langue')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('all_levels', 'Tous niveaux')], default='all_levels', max_length=20, verbose_name='niveau')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/%Y/%m/', verbose_name='miniature')),
                ('promo_video', models.FileField(blank=True, null=True, upload_to='courses/promo/%Y/%m/', verbose_name='vidéo de présentation')),
                ('pricing_model', models.CharField(choices=[('free', 'Gratuit'), ('one_time', 'Achat unique'), ('subscription', 'Abonnement')], default='one_time', max_length=20, verbose_name='modèle tarifaire')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='prix (FCFA)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='prix promotionnel (FCFA)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'En attente de validation'), ('published', 'Publié'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='statut')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motif de rejet')),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='catégorie')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='formateur')),
            ],
            options={
                'verbose_name': 'cours',
                'verbose_name_plural': 'cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course')),
            ],
            options={
                'verbose_name': 'chapitre',
                'verbose_name_plural': 'chapitres',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('purchase', 'Achat'), ('subscription', 'Abonnement'), ('free', 'Gratuit'), ('affiliate', 'Via affiliation')], default='purchase', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('content_type', models.CharField(choices=[('video', 'Vidéo'), ('text', 'Texte / Article'), ('quiz', 'Quiz'), ('pdf', 'Document PDF')], default='video', max_length=20, verbose_name='type de contenu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='courses/videos/%Y/%m/', verbose_name='fichier vidéo')),
                ('video_url', models.URLField(blank=True, verbose_name='URL vidéo (stockage cloud/CDN)')),
                ('video_duration_seconds', models.PositiveIntegerField(default=0, verbose_name='durée (secondes)')),
                ('text_content', models.TextField(blank=True, verbose_name='contenu texte')),
                ('is_preview', models.BooleanField(default=False, help_text='Visible sans achat du cours', verbose_name='aperçu gratuit')),
                ('is_downloadable', models.BooleanField(default=False, verbose_name='téléchargement autorisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.chapter')),
            ],
            options={
                'verbose_name': 'leçon',
                'verbose_name_plural': 'leçons',
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_position_seconds', models.PositiveIntegerField(default=0, verbose_name='dernière position (secondes)')),
                ('watched_seconds_total', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'progression de leçon',
                'verbose_name_plural': 'progressions de leçon',
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('file', models.FileField(upload_to='courses/resources/%Y/%m/', verbose_name='fichier')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'ressource de leçon',
                'verbose_name_plural': 'ressources de leçon',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_seconds', models.PositiveIntegerField(default=0, verbose_name='horodatage vidéo (secondes)')),
                ('content', models.TextField(verbose_name='contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['lesson', 'timestamp_seconds'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'liste de souhaits',
                'verbose_name_plural': 'listes de souhaits',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'is_featured'], name='courses_cou_status_ee4b06_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='courses_cou_categor_108713_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('chapter', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('enrollment', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('student', 'course')},
        ),
    ]
